# Generated by Django 5.2.1 on 2025-05-18 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botadmin', '0002_category_word_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repeatsession',
            name='words',
        ),
        migrations.AddField(
            model_name='repeatsession',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repeat_sessions', to='botadmin.category'),
        ),
    ]
